name = "chatwork-slack-bridge"
main = "src/index.ts"
account_id = "a23d3fb78fbecdfc05c9cd5d56afef4a"
compatibility_date = "2024-12-01"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "6da6be46573f498c82c231d477f90d47"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
